name: Deploy OpenFLAME preview

on:
  push:
    branches:
      - open-flame

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.1

      - name: Build Zola site
        uses: getzola/github-pages@066755243e69f508fd1a74739fbf1a65f656c790
        with:
          working_directory: website
          zola_version: v0.19.2
          build_flags: --base-url https://sagar-bharadwaj-ks.github.io/csd-blog

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
